import type { ManualReviewItem } from '@spa-bridge/core-model';

import type { EnterpriseParityArtifacts, GeneratedFileSpec, TargetGenerationRequest } from '../types.js';
import { createFileSpec } from '../write-plan/generated-file-spec-factory.js';
import { EnvironmentContractBuilder } from './environment-contract-builder.js';
import { RegistryMigrationPlanner } from './registry-migration-planner.js';
import { SourceScriptTranslator } from './source-script-translator.js';
import { PackageManagerParityPlanner } from './package-manager-parity-planner.js';

const header = (label: string): string => `# Generated by SPA-Bridge. ${label}\n`;

const buildNpmrcContent = (lines: string[], fallback: string): string =>
  lines.length > 0 ? `${header('Private registry routing only; no raw secrets are stored.')}${lines.join('\n')}\n` : `${header(fallback)}`;

const buildEnvExample = (lines: string[]): string =>
  lines.length > 0 ? `${header('Fill values locally or through CI secret management.')}${lines.join('\n')}\n` : `${header('No source environment variables were detected.')}`;

const toReviewItem = (id: string, title: string, description: string): ManualReviewItem => ({
  id,
  title,
  description,
  status: 'open',
});

export class EnterpriseArtifactMaterializer {
  constructor(
    private readonly registryPlanner = new RegistryMigrationPlanner(),
    private readonly scriptTranslator = new SourceScriptTranslator(),
    private readonly environmentBuilder = new EnvironmentContractBuilder(),
    private readonly packageManagerPlanner = new PackageManagerParityPlanner(),
  ) {}

  buildArtifacts(request: TargetGenerationRequest): EnterpriseParityArtifacts {
    const registryMigrationPlan = this.registryPlanner.plan(request.sourceNpmrcFiles);
    const scriptMigrationPlan = this.scriptTranslator.translate(request.sourceScripts);
    const environmentContractReport = this.environmentBuilder.build(request.sourceEnvironmentVariables);
    const packageManagerParityReport = this.packageManagerPlanner.plan(request.sourcePackageManager);
    const manualReviewItems =
      registryMigrationPlan.manualReviewItems.length
      + scriptMigrationPlan.manualReviewCount
      + environmentContractReport.manualReviewCount
      + (packageManagerParityReport.manualReviewRequired ? 1 : 0);

    return {
      registryMigrationPlan,
      scriptMigrationPlan,
      environmentContractReport,
      packageManagerParityReport,
      summary: {
        registrySafeEntries: registryMigrationPlan.safeEntryCount,
        registrySecretPlaceholders: registryMigrationPlan.secretEntryCount,
        generatedScripts: Object.keys(scriptMigrationPlan.targetScripts).length,
        reviewedScripts: scriptMigrationPlan.manualReviewCount,
        environmentVariables: environmentContractReport.variables.length,
        secretEnvironmentVariables: environmentContractReport.secretCount,
        packageManager: packageManagerParityReport.selected.name,
        packageManagerVersion: packageManagerParityReport.selected.version,
        manualReviewItems,
      },
    };
  }

  materialize(artifacts: EnterpriseParityArtifacts): GeneratedFileSpec[] {
    return [
      createFileSpec({
        path: '.npmrc',
        kind: 'registry',
        content: buildNpmrcContent(artifacts.registryMigrationPlan.safeTargetNpmrcLines, 'No private registry routing was detected.'),
        status: 'metadata',
      }),
      createFileSpec({
        path: '.npmrc.example',
        kind: 'registry',
        content: buildNpmrcContent(artifacts.registryMigrationPlan.exampleNpmrcLines, 'No private registry placeholders were detected.'),
        status: 'metadata',
      }),
      createFileSpec({
        path: '.env.example',
        kind: 'environment',
        content: buildEnvExample(artifacts.environmentContractReport.exampleEnvLines),
        status: 'metadata',
      }),
      createFileSpec({
        path: 'src/review/registry-migration-report.json',
        kind: 'review',
        content: JSON.stringify(artifacts.registryMigrationPlan, null, 2) + '\n',
        status: artifacts.registryMigrationPlan.secretEntryCount > 0 ? 'review' : 'metadata',
      }),
      createFileSpec({
        path: 'src/review/script-migration-report.json',
        kind: 'review',
        content: JSON.stringify(artifacts.scriptMigrationPlan, null, 2) + '\n',
        status: artifacts.scriptMigrationPlan.manualReviewCount > 0 ? 'review' : 'metadata',
      }),
      createFileSpec({
        path: 'src/review/environment-contract-report.json',
        kind: 'review',
        content: JSON.stringify(artifacts.environmentContractReport, null, 2) + '\n',
        status: artifacts.environmentContractReport.manualReviewCount > 0 ? 'review' : 'metadata',
      }),
      createFileSpec({
        path: 'src/review/package-manager-parity-report.json',
        kind: 'review',
        content: JSON.stringify(artifacts.packageManagerParityReport, null, 2) + '\n',
        status: artifacts.packageManagerParityReport.manualReviewRequired ? 'review' : 'metadata',
      }),
    ];
  }

  createManualReviewItems(artifacts: EnterpriseParityArtifacts): ManualReviewItem[] {
    return [
      ...artifacts.registryMigrationPlan.manualReviewItems.map((item) => toReviewItem(item.id, 'Review private registry credential setup', item.safeSummary)),
      ...artifacts.scriptMigrationPlan.decisions
        .filter((decision) => decision.manualReviewRequired)
        .map((decision) =>
          toReviewItem(
            `script-${decision.sourceName.replace(/[^A-Za-z0-9_-]/g, '-')}`,
            `Review source script '${decision.sourceName}'`,
            `${decision.reasonCode}: configure an equivalent Next.js-safe workflow if this script is still required.`,
          ),
        ),
      ...artifacts.environmentContractReport.variables
        .filter((variable) => variable.manualReviewRequired)
        .map((variable) =>
          toReviewItem(
            `env-${variable.targetName.replace(/[^A-Za-z0-9_-]/g, '-')}`,
            `Review environment variable '${variable.targetName}'`,
            `${variable.classification} variable is represented by placeholder only; configure the real value outside generated source control.`,
          ),
        ),
      ...(artifacts.packageManagerParityReport.manualReviewRequired
        ? [
            toReviewItem(
              'package-manager-parity-review',
              'Review generated package manager parity',
              `Package manager '${artifacts.packageManagerParityReport.targetPackageManagerField}' was selected with ${artifacts.packageManagerParityReport.selected.confidence} confidence.`,
            ),
          ]
        : []),
    ].sort((left, right) => left.id.localeCompare(right.id));
  }
}
