import type {
  GeneratedFileSpec,
  NormalizedTargetDraftBundle,
  TargetDependencyManifest,
  TargetGenerationRequest,
  TargetStrategyDescriptor,
} from '../types.js';

const baseDependencies = {
  react: '18.2.0',
  'react-dom': '18.2.0',
  'react-router-dom': '6.30.1',
};

const baseDevDependencies = {
  '@types/react': '18.3.12',
  '@types/react-dom': '18.3.1',
  '@types/node': '22.15.0',
  '@vitejs/plugin-react': '4.3.4',
  typescript: '5.8.3',
  vite: '5.4.11',
  less: '4.2.0',
};

const makeFile = (
  path: string,
  kind: GeneratedFileSpec['kind'],
  content: string,
  sourceRefs: GeneratedFileSpec['sourceRefs'] = [],
  overwrite = true,
): GeneratedFileSpec => ({
  path,
  kind,
  content,
  sourceRefs,
  generatedRefs: [{ kind: 'generated', path }],
  traceRefs: [],
  overwrite,
  status: 'generated',
});

const buildPackageJson = (
  request: TargetGenerationRequest,
  manifest: TargetDependencyManifest,
): string =>
  JSON.stringify(
    {
      name: request.projectName ?? 'spa-bridge-react-target',
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc -b && vite build',
        preview: 'vite preview',
      },
      dependencies: manifest.dependencies,
      devDependencies: manifest.devDependencies,
    },
    null,
    2,
  ) + '\n';

const buildTsconfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        useDefineForClassFields: true,
        jsx: 'react-jsx',
        lib: ['DOM', 'DOM.Iterable', 'ES2022'],
        allowJs: false,
        skipLibCheck: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        strict: true,
        forceConsistentCasingInFileNames: true,
        module: 'ESNext',
        moduleResolution: 'Bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        types: ['vite/client'],
      },
      include: ['src'],
    },
    null,
    2,
  ) + '\n';

const buildTsconfigNode = (): string =>
  JSON.stringify(
    {
      extends: './tsconfig.json',
      compilerOptions: {
        noEmit: false,
        composite: false,
        types: ['node'],
      },
      include: ['vite.config.ts'],
    },
    null,
    2,
  ) + '\n';

const buildViteConfig = (): string => `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;

const buildIndexHtml = (projectName: string): string => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

const buildMainTsx = (): string => `import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App.js';
import './styles.css';
import './source-styles.js';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`;

const buildAppTsx = (projectName: string): string => `export const App = () => {
  return (
    <main className="app-shell">
      <h1>${projectName}</h1>
      <p>Target React scaffold generated by SPA-Bridge.</p>
    </main>
  );
};
`;

const buildStyles = (): string => `.app-shell {
  font-family: Inter, system-ui, sans-serif;
  padding: 2rem;
}
`;

const buildStrategy = (id: TargetStrategyDescriptor['id'], defaultStrategy: boolean): TargetStrategyDescriptor => ({
  id,
  displayName: 'Vite + React + TypeScript',
  description: 'Default deterministic Vite scaffold with React 18 and TypeScript.',
  defaultStrategy,
  supportedStateStrategies: ['service', 'signals', 'store', 'local', 'unknown'],
  capabilities: [
    'base-scaffold',
    'routing',
    'state-adapters',
    'component-materialization',
    'review-stubs',
  ],
  exactDependencies: {
    ...baseDependencies,
  },
  createScaffoldFiles: ({ request, normalizedDrafts, dependencyManifest }): GeneratedFileSpec[] => {
    const projectName = normalizedDrafts.projectName || request.projectName || 'spa-bridge-react-target';

    return [
      makeFile('package.json', 'scaffold', buildPackageJson({ ...request, projectName }, dependencyManifest)),
      makeFile('tsconfig.json', 'scaffold', buildTsconfig()),
      makeFile('tsconfig.node.json', 'scaffold', buildTsconfigNode()),
      makeFile('vite.config.ts', 'scaffold', buildViteConfig()),
      makeFile('index.html', 'scaffold', buildIndexHtml(projectName)),
      makeFile('src/main.tsx', 'scaffold', buildMainTsx()),
      makeFile('src/App.tsx', 'scaffold', buildAppTsx(projectName)),
      makeFile('src/styles.css', 'scaffold', buildStyles()),
      makeFile('src/source-styles.ts', 'scaffold', '/* Angular source style imports are added by the CLI resource copier. */\n'),
    ];
  },
});

export const createViteReactTypeScriptStrategy = (): TargetStrategyDescriptor =>
  buildStrategy('vite-react-typescript', true);

export const createReactDefaultStrategy = (): TargetStrategyDescriptor =>
  buildStrategy('react-default', false);

export const viteReactTypeScriptStrategyId = 'vite-react-typescript' as const;

export const createViteReactDependencyManifest = (): TargetDependencyManifest => ({
  dependencies: { ...baseDependencies },
  devDependencies: { ...baseDevDependencies },
  rationale: {
    react: 'Core UI runtime for the generated target project.',
    'react-dom': 'Browser rendering for React root mounting.',
    'react-router-dom': 'Default route support for converted navigation.',
    '@types/react': 'TypeScript declarations for React components.',
    '@types/react-dom': 'TypeScript declarations for DOM rendering APIs.',
    '@vitejs/plugin-react': 'Vite fast refresh and JSX transform support.',
    typescript: 'TypeScript compiler for the generated target project.',
    vite: 'Deterministic dev-server and build pipeline.',
    less: 'LESS preprocessing support for Angular styles carried into the React target.',
  },
});
